export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_NOT_AUTHENTICATED = "SET_USER_NOT_AUTHENTICATED";

export const GET_MAIN_LISTING_SUCCESS = "GET_MAIN_LISTING_SUCCESS";
export const GET_MAIN_LISTING_FAILURE = "GET_MAIN_LISTING_FAILURE";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const GET_LISTING_SUCCESS = "GET_LISTING_SUCCESS";
export const GET_LISTING_FAILURE = "GET_LISTING_FAILURE";