export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_NOT_AUTHENTICATED = "SET_USER_NOT_AUTHENTICATED";
